// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api.Models
{
    public partial class Region
    {
        public Region()
        {
            Countries = new HashSet<Country>();
            SubRegions = new HashSet<SubRegion>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("Region")]
        public virtual ICollection<Country> Countries { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<SubRegion> SubRegions { get; set; }
    }
}